[project]
name = "design-patterns"
version = "0.1.0"
description = "ArjanCodes Python Design Patterns YouTube series"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[tool.uv.workspace]
members = [
    "patterns/specification",
    "patterns/retry",
    "patterns/strategy",
    "patterns/observer",
    "patterns/template",
    "patterns/bridge",
    "patterns/object_pool",
    "patterns/singleton",
    "patterns/factory",
]
